# Generated by Django 6.0.3 on 2026-03-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-created_at'], 'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AddField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='experiences/'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Maximum number of participants'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this experience from listings'),
        ),
    ]
